### ISSUE TITLE
.mat pose files missing in generating dataset 

### ISSUE THREAD

**Issue by 1ssb** [ayushtewari/DFM#1]
Hi, the torch version is causing some issues. Is it kindly posible for you to upload an environment.yml?

**Comment by tianweiy** [comment]
could you elaborate on the issues you get? environment.yml file won't make a difference I guess.

**Comment by 1ssb** [comment]
So, the fundamental problem is that (I can't speak for others) I use torch 2.1 and most of the package systems are reliant on that. So, to pip install 2.0.1 is an issue, which are causing clashes with many other library systems.

So, to just recreate the inference pipeline, I am having to replace most of these libraries which is trying. If you could specify the .yml config with their versions (or simply listing the versions in the requirements file) then its significantly easier to self-contain as I can find a way to sandbox it.

**Comment by tianweiy** [comment]
I would suggest creating a new conda (with all libraries) as we did in the README (this is the one that we know works).

**Comment by 1ssb** [comment]
Right, so tried that, it leads to this error on my local pc (no package conflicts):

FileNotFoundError: [Errno 2] No such file or directory: 'path/test.mat'

Can you help?

**Comment by tianweiy** [comment]
full command + log (i.e. a screenshot of everything you run + the output) please

**Comment by 1ssb** [comment]
Here it is:

```python
(dfm) usr:~/Desktop/DFM$ python experiment_scripts/re_results.py dataset=realestate batch_size=1 num_target=1 num_context=1 model_type=dit feats_cond=true sampling_type=simple max_scenes=10000 stage=test use_guidance=true guidance_scale=2.0 temperature=0.85 sampling_steps=50 name=re10k_inference image_size=128 checkpoint_path=files/re10k_model.pt wandb=local
``` 
Log:


```powershell
(dfm) usr:~/Desktop/DFM$ python experiment_scripts/re_results.py dataset=realestate batch_size=1 num_target=1 num_context=1 model_type=dit feats_cond=true sampling_type=simple max_scenes=10000 stage=test use_guidance=true guidance_scale=2.0 temperature=0.85 sampling_steps=50 name=re10k_inference image_size=128 checkpoint_path=files/re10k_model.pt wandb=local
/home/users/usr/anaconda3/envs/dfm/lib/python3.9/site-packages/hydra/_internal/defaults_list.py:251: UserWarning: In 'config': Defaults list is missing `_self_`. See https://hydra.cc/docs/1.2/upgrades/1.0_to_1.1/default_composition_order for more information
  warnings.warn(msg, UserWarning)
run dir: /tmp
loading pose file
Error executing job with overrides: ['dataset=realestate', 'batch_size=1', 'num_target=1', 'num_context=1', 'model_type=dit', 'feats_cond=true', 'sampling_type=simple', 'max_scenes=10000', 'stage=test', 'use_guidance=true', 'guidance_scale=2.0', 'temperature=0.85', 'sampling_steps=50', 'name=re10k_inference', 'image_size=128', 'checkpoint_path=files/re10k_model.pt', 'wandb=local']
Traceback (most recent call last):
  File "/home/users/usr/anaconda3/envs/dfm/lib/python3.9/site-packages/scipy/io/matlab/_mio.py", line 39, in _open_file
    return open(file_like, mode), True
FileNotFoundError: [Errno 2] No such file or directory: 'path/test.mat'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/users/usr/Desktop/DFM/experiment_scripts/re_results.py", line 559, in <module>
    train()
  File "/home/users/usr/anaconda3/envs/dfm/lib/python3.9/site-packages/hydra/main.py", line 94, in decorated_main
    _run_hydra(
  File "/home/users/usr/anaconda3/envs/dfm/lib/python3.9/site-packages/hydra/_internal/utils.py", line 394, in _run_hydra
    _run_app(
  File "/home/users/usr/anaconda3/envs/dfm/lib/python3.9/site-packages/hydra/_internal/utils.py", line 457, in _run_app
    run_and_report(
  File "/home/users/usr/anaconda3/envs/dfm/lib/python3.9/site-packages/hydra/_internal/utils.py", line 223, in run_and_report
    raise ex
  File "/home/users/usr/anaconda3/envs/dfm/lib/python3.9/site-packages/hydra/_internal/utils.py", line 220, in run_and_report
    return func()
  File "/home/users/usr/anaconda3/envs/dfm/lib/python3.9/site-packages/hydra/_internal/utils.py", line 458, in <lambda>
    lambda: hydra.run(
  File "/home/users/usr/anaconda3/envs/dfm/lib/python3.9/site-packages/hydra/_internal/hydra.py", line 132, in run
    _ = ret.return_value
  File "/home/users/usr/anaconda3/envs/dfm/lib/python3.9/site-packages/hydra/core/utils.py", line 260, in return_value
    raise self._return_value
  File "/home/users/usr/anaconda3/envs/dfm/lib/python3.9/site-packages/hydra/core/utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
  File "/home/users/usr/Desktop/DFM/experiment_scripts/re_results.py", line 50, in train
    dataset = data_io.get_dataset(cfg)
  File "/home/users/usr/Desktop/DFM/data_io/__init__.py", line 24, in get_dataset
    return RealEstate10kDatasetOM(
  File "/home/users/usr/Desktop/DFM/data_io/realestate10k.py", line 96, in __init__
    self.all_cam_params = scipy.io.loadmat(pose_file)
  File "/home/users/usr/anaconda3/envs/dfm/lib/python3.9/site-packages/scipy/io/matlab/_mio.py", line 225, in loadmat
    with _open_file_context(file_name, appendmat) as f:
  File "/home/users/usr/anaconda3/envs/dfm/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/home/users/usr/anaconda3/envs/dfm/lib/python3.9/site-packages/scipy/io/matlab/_mio.py", line 17, in _open_file_context
    f, opened = _open_file(file_like, appendmat, mode)
  File "/home/users/usr/anaconda3/envs/dfm/lib/python3.9/site-packages/scipy/io/matlab/_mio.py", line 47, in _open_file
    raise OSError(
OSError: Reader needs file name or open file-like object
``` 

Could you kindly check this. Is it supposed to be a file generated by or with the dataset?

**Comment by 1ssb** [comment]
The pose_file line is commented out in the realestate10k code.
