### ISSUE TITLE
preparing CO3D dataset

### ISSUE THREAD

**Issue by junsukha** [ayushtewari/DFM#17]
When I run `python data_io/co3d_new.py --generate_info_file  --generate_camera_quality_file --generate_per_scene_scale --dataset_root CO3D_ROOT `,  

I get the following error:

```
Traceback (most recent call last):
  File "/home/jun/Documents/DFM/data_io/co3d_new.py", line 592, in <module>
    init_info_file(categories, args.dataset_root)
  File "/home/jun/Documents/DFM/data_io/co3d_new.py", line 381, in init_info_file
    dataset_map = get_dataset_map(dataset_root, category, 'fewview_dev')
  File "/home/jun/Documents/DFM/data_io/co3d_new.py", line 34, in get_dataset_map
    dataset_map_provider = JsonIndexDatasetMapProviderV2(
  File "<string>", line 15, in __init__
  File "/home/jun/Documents/DFM/data_io/co3d/json_index_dataset_map_provider_v2.py", line 214, in __post_init__
    dataset_map = self._load_category(self.category)
  File "/home/jun/Documents/DFM/data_io/co3d/json_index_dataset_map_provider_v2.py", line 234, in _load_category
    raise ValueError(
ValueError: Looking for frame annotations in CO3D_ROOT/hydrant/frame_annotations.jgz. Please specify a correct dataset_root folder. Note: By default the root folder is taken from the CO3DV2_DATASET_ROOT environment variable.
```

Any ideas??
Thanks!

**Comment by junsukha** [comment]
Solved!
